###
GET http://localhost:8000/products

###
POST http://localhost:8000/products
Content-Type: application/json

{
  "name": "Product 1",
  "price": 10.99
}

###
POST http://localhost:8000/products
Content-Type: application/json

{
  "name": "Product 2",
  "price": 17.99
}


###
POST http://localhost:8000/products
Content-Type: application/json

{
  "name": "Product 3",
  "price": 25.99
}

